dbt_demo_framework:
target: dev
outputs:
  dev:
    type: snowflake
    account: 'not needed'
    user: 'not needed'
    role: DBTROLE
    database: DBT_DB_DEV
    schema: BRONZE
    warehouse: DBT_WH