{% macro load_models_yaml() %}
    {% if execute %}
        {# Building Audit Table Relation #}
        {%- set database = var("yaml_load_database", target.database) -%}
        {%- set schema = var("yaml_load_schema", "LOGGING") -%}
        {%- set table_identifier = var("yaml_load_table_name", "MODEL_YAML") -%}
        {%- set relation = database ~ '.' ~ schema ~ '.' ~ table_identifier -%}

        {# Extract Models from 'graph' context variable #}
        {%- set models = graph.nodes.values() | selectattr("resource_type", "equalto", "model") | selectattr("package_name", "equalto", project_name) | list -%}

        {% if models != [] %}

        {# Building Create Model Yaml Table Query #}
        {{ log("Executing 'CREATE TABLE SQL' for Model Yaml Table", info=True) }}
        {% call statement('model_yaml_create_table_sql') %}
            CREATE TABLE IF NOT EXISTS {{ relation }} (
                MODEL_UID VARCHAR(2000) COMMENT 'UID generated by dbt for each Model.',
                MODEL_NAME VARCHAR(2000) COMMENT 'Name of the dbt model.',
                YAML VARIANT COMMENT 'Model YAML structure in JSON format'
            )
            ;
        {% endcall %}
        {{ log("Model Yaml Table '" ~ relation ~ "' Created Successfully", info=True) }}

        {# Building Truncate Model Yaml Table Query #}
        {{ log("Executing 'TRUNCATE TABLE SQL' for Model Yaml Table", info=True) }}
        {% call statement('model_yaml_table_truncate_sql') %}
            TRUNCATE TABLE {{ relation }}
            ;
        {% endcall %}

        {# Building Insert Into Model Yaml Table Query #}
        {%- set insert_content_sql = get_model_yaml_insert_content_sql(models) -%}

        {{ log("Executing 'INSET INTO SQL' for Model Yaml Table", info=True) }}
        {% call statement('model_yaml_table_insert_sql') %}
            INSERT INTO {{ relation }} (
                MODEL_UID,
                MODEL_NAME,
                YAML
            )
            {{ insert_content_sql }}
            ;
        {% endcall %}

        {% endif %}
    {% endif %}
    
{% endmacro %}

{% macro get_model_yaml_insert_content_sql(models) %}
    {# Building Select Query for Load Yaml Macro #}
    {% set select_sql %}
    SELECT
        $1,
        $2,
        PARSE_JSON($3)
    FROM VALUES

    {% for model in models %}
        (
            '{{ model.unique_id }}', {# 1. model_unique_id #}
            '{{ model.name }}', {# 2. model_name #}
            '{{ tojson(model)  | replace("\\", "\\\\") | replace("'", "\\'") | replace('"', '\\"') }}' {# 3. model_yaml #}
        )
        {%- if not loop.last %},{%- endif %}

    {% endfor %}
    {% endset %}

    {{ select_sql }}

{% endmacro %}