{% macro load_dbt_model_metadata() %}
    {% if execute %}
        {{ log("MODEL METADATA MACRO EXECUTED", info=True) }}

        {# Building Model Metadata Table Relation #}
        {%- set relation = model.relation_name -%}

        {# Extract Models from 'graph' context variable #}
        {%- set models = graph.nodes.values() | selectattr("resource_type", "equalto", "model") | selectattr("package_name", "equalto", project_name) | list -%}

        {% if models != [] %}

        {# Building Create Model Meatadata Table Query #}
        {{ log("Executing 'CREATE TABLE SQL' for Model Metadata Table", info=True) }}
        {% call statement('model_metadata_table_create_sql') %}
            CREATE TABLE IF NOT EXISTS {{ relation }} (
                MODEL_UID VARCHAR(2000) COMMENT 'UID generated by dbt for each Model.',
                MODEL_NAME VARCHAR(2000) COMMENT 'Name of the dbt model.',
                YAML OBJECT COMMENT 'Model YAML structure in JSON format'
            )
            ;
        {% endcall %}
        {{ log("Model Metadata Table '" ~ relation ~ "' Created Successfully", info=True) }}

        {# Building Truncate Model Metadata Table Query #}
        {{ log("Executing 'TRUNCATE TABLE SQL' for Model Metadata Table", info=True) }}
        {% call statement('model_metadata_table_truncate_sql') %}
            TRUNCATE TABLE {{ relation }}
            ;
        {% endcall %}

        {# Building Insert Into Model Metadata Table Query #}
        {%- set insert_content_sql = get_model_metadata_insert_content_sql(models) -%}

        {{ log("Executing 'INSET INTO SQL' for Model Metadata Table", info=True) }}
        {% call statement('model_metadata_table_insert_sql') %}
            INSERT INTO {{ relation }} (
                MODEL_UID,
                MODEL_NAME,
                YAML
            )
            {{ insert_content_sql }}
            ;
        {% endcall %}

        {% endif %}
    {% endif %}
    
{% endmacro %}

{% macro get_model_metadata_insert_content_sql(models) %}
    {# Building Select Query for DBT Model Metadata Macro #}
    {% set select_sql %}
    SELECT
        $1,
        $2,
        PARSE_JSON($3)
    FROM VALUES

    {% for model in models %}
        (
            '{{ model.unique_id }}', {# 1. model_unique_id #}
            '{{ model.name }}', {# 2. model_name #}
            '{{ tojson(model)  | replace("\\", "\\\\") | replace("'", "\\'") | replace('"', '\\"') }}' {# 3. model_yaml #}
        )
        {%- if not loop.last %},{%- endif %}

    {% endfor %}
    {% endset %}

    {{ select_sql }}

{% endmacro %}